"""
schemes_loader.py — Run this ONCE from your backend folder to populate
the schemes table from the MyScheme government dataset JSON.

Usage:
    cd D:\govt_sahay\backend
    python schemes_loader.py

Dataset source: https://www.myscheme.gov.in  (open government data)
We ship a curated 50-scheme JSON file alongside this script.
"""

import json
import os
import sys
from config import supabase

# ── Embedded dataset (50 real schemes from MyScheme / data.gov.in) ────────────
SCHEMES = [
  {"name":"PM Kisan Samman Nidhi","description":"Income support of Rs.6,000 per year to small and marginal farmer families across India in three equal installments.","benefits":"Rs.6,000 per year paid in 3 installments of Rs.2,000 directly to bank account via DBT","min_age":18,"max_age":70,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Farmer"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmkisan.gov.in"},
  {"name":"PM Awas Yojana (Urban)","description":"Affordable housing for EWS/LIG/MIG beneficiaries in urban areas with interest subsidy on home loans.","benefits":"Interest subsidy up to Rs.2.67 lakh on home loans; credit-linked subsidy for home construction","min_age":21,"max_age":65,"income_limit":300000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC","General"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmaymis.gov.in"},
  {"name":"Beti Bachao Beti Padhao","description":"Scheme to address declining child sex ratio and promote welfare, education and survival of the girl child.","benefits":"Scholarships, awareness campaigns, cash incentives for girl child education and survival","min_age":0,"max_age":18,"income_limit":500000,"genders":["Female"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://wcd.nic.in"},
  {"name":"National Scholarship Portal (Minority)","description":"Merit and means based scholarships for students from minority communities to pursue education.","benefits":"Pre-matric: Rs.10,000/year; Post-matric: Rs.20,000/year; Merit-cum-means: Rs.20,000/year","min_age":6,"max_age":25,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Student"],"religions":["Muslim","Christian","Sikh","Buddhist","Parsi"],"required_docs":["aadhar","income","caste"],"official_url":"https://scholarships.gov.in"},
  {"name":"Pradhan Mantri Mudra Yojana","description":"Provides loans up to Rs.10 lakh to non-corporate, non-farm small and micro enterprises.","benefits":"Shishu: up to Rs.50,000; Kishore: Rs.50,000–5 lakh; Tarun: Rs.5–10 lakh — all collateral free","min_age":18,"max_age":65,"income_limit":1000000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Self-employed","Entrepreneur","Businessman"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://mudra.org.in"},
  {"name":"Ayushman Bharat PM-JAY","description":"World's largest government-funded health insurance providing coverage of Rs.5 lakh per family per year.","benefits":"Rs.5 lakh health cover per family per year for 1,574 medical procedures including hospitalisation","min_age":0,"max_age":100,"income_limit":250000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmjay.gov.in"},
  {"name":"Post-Matric Scholarship for SC Students","description":"Financial assistance to SC students pursuing post-matriculation or post-secondary education.","benefits":"Maintenance allowance + tuition fee reimbursement + book allowance up to Rs.1,200/year","min_age":15,"max_age":30,"income_limit":250000,"genders":["all"],"states":["all"],"castes":["SC"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","caste"],"official_url":"https://scholarships.gov.in"},
  {"name":"PM Jeevan Jyoti Bima Yojana","description":"Renewable one-year life insurance scheme offering Rs.2 lakh coverage at Rs.436/year premium.","benefits":"Rs.2 lakh life insurance cover; renewable annually; auto-debit from bank account","min_age":18,"max_age":50,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://jansuraksha.gov.in"},
  {"name":"Sukanya Samriddhi Yojana","description":"Small savings scheme for the girl child to secure funds for education and marriage expenses.","benefits":"8.2% interest rate (highest among small savings); tax-free maturity; Section 80C deduction","min_age":0,"max_age":10,"income_limit":1000000,"genders":["Female"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://nsiindia.gov.in"},
  {"name":"NMMS Scholarship","description":"National Means-cum-Merit Scholarship for meritorious students from economically weaker sections in class 9–12.","benefits":"Rs.12,000 per year (Rs.1,000 per month) from class 9 to 12 — paid directly to bank account","min_age":13,"max_age":18,"income_limit":150000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://scholarships.gov.in"},
  {"name":"PM Suraksha Bima Yojana","description":"Accident insurance scheme offering Rs.2 lakh accidental death and disability cover at Rs.20/year.","benefits":"Rs.2 lakh for accidental death/permanent disability; Rs.1 lakh for partial disability","min_age":18,"max_age":70,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://jansuraksha.gov.in"},
  {"name":"Atal Pension Yojana","description":"Government-backed pension scheme for workers in the unorganised sector with guaranteed monthly pension.","benefits":"Guaranteed pension of Rs.1,000–5,000/month after age 60; government co-contributes 50% for first 5 years","min_age":18,"max_age":40,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Daily Wage Worker","Agricultural Laborer","Self-employed"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://npscra.nsdl.co.in"},
  {"name":"Kisan Credit Card","description":"Provides short-term credit support to farmers for crop cultivation, allied activities, and consumption needs.","benefits":"Revolving credit up to Rs.3 lakh at 7% interest (4% with interest subvention); crop insurance included","min_age":18,"max_age":75,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Farmer","Agricultural Laborer"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmkisan.gov.in"},
  {"name":"National Rural Employment Guarantee (MGNREGS)","description":"Guarantees 100 days of unskilled manual wage employment per year to every rural household.","benefits":"100 days of guaranteed employment at minimum wage; compensation if work not provided within 15 days","min_age":18,"max_age":100,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Agricultural Laborer","Daily Wage Worker","Unemployed"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://nrega.nic.in"},
  {"name":"PM Ujjwala Yojana","description":"Provides LPG connections to women from below poverty line households to replace polluting cooking fuels.","benefits":"Free LPG connection with cylinder and regulator; first refill and hotplate subsidised","min_age":18,"max_age":100,"income_limit":100000,"genders":["Female"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Homemaker","Agricultural Laborer","Daily Wage Worker"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmuy.gov.in"},
  {"name":"Startup India Seed Fund","description":"Financial assistance for startups for proof of concept, prototype development, product trials, and market entry.","benefits":"Up to Rs.20 lakh for proof of concept; up to Rs.50 lakh for prototype and product trials","min_age":18,"max_age":45,"income_limit":10000000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Entrepreneur","Self-employed","Businessman"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://seedfund.startupindia.gov.in"},
  {"name":"PM SVANidhi (Street Vendor Loan)","description":"Working capital loans for street vendors to resume livelihood affected by COVID-19 pandemic.","benefits":"Rs.10,000 initial loan; Rs.20,000 on timely repayment; Rs.50,000 on further repayment — collateral free","min_age":18,"max_age":65,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Self-employed","Daily Wage Worker"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://pmsvanidhi.mohua.gov.in"},
  {"name":"National Apprenticeship Promotion Scheme","description":"Promotes apprenticeship training by sharing 25% of stipend cost with employers to boost industrial training.","benefits":"Government reimburses 25% of stipend (max Rs.1,500/month); skill certification on completion","min_age":14,"max_age":25,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Student","Unemployed"],"religions":["all"],"required_docs":["aadhar","dob","basic"],"official_url":"https://apprenticeshipindia.gov.in"},
  {"name":"Pradhan Mantri Kaushal Vikas Yojana","description":"Skill certification scheme to enable youth to take up industry-relevant skill training and earn better livelihoods.","benefits":"Free short-term skill training; recognition of prior learning; Rs.8,000 average reward on certification","min_age":15,"max_age":45,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Unemployed","Student","Daily Wage Worker"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://pmkvyofficial.org"},
  {"name":"Scholarship for OBC Students (Post-Matric)","description":"Financial assistance to OBC students pursuing post-matriculation studies in India.","benefits":"Maintenance allowance + tuition fees; hostellers: Rs.1,000/month; day scholars: Rs.570/month","min_age":15,"max_age":30,"income_limit":100000,"genders":["all"],"states":["all"],"castes":["OBC"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","caste"],"official_url":"https://scholarships.gov.in"},
  {"name":"PM Fasal Bima Yojana","description":"Crop insurance scheme providing financial support to farmers suffering crop loss due to natural calamities.","benefits":"Kharif: 2% premium; Rabi: 1.5% premium; commercial crops: 5% — rest paid by government","min_age":18,"max_age":70,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Farmer"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmfby.gov.in"},
  {"name":"Deen Dayal Upadhyaya Grameen Kaushalya Yojana","description":"Placement-linked skill training programme targeting rural youth from poor families.","benefits":"Free residential training; placement assistance; post-placement support for 2 months; min Rs.6,000/month salary","min_age":15,"max_age":35,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Unemployed","Daily Wage Worker"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://ddugky.gov.in"},
  {"name":"STAND UP India","description":"Facilitates bank loans between Rs.10 lakh and Rs.1 crore to SC/ST and women entrepreneurs.","benefits":"Loans from Rs.10 lakh to Rs.1 crore at low interest; repayment up to 7 years; working capital support","min_age":18,"max_age":65,"income_limit":2000000,"genders":["all"],"states":["all"],"castes":["SC","ST"],"occupations":["Entrepreneur","Self-employed","Businessman"],"religions":["all"],"required_docs":["aadhar","income","caste"],"official_url":"https://www.standupmitra.in"},
  {"name":"National Overseas Scholarship (SC)","description":"Scholarship for SC students to pursue PhD or Post-Doctoral research abroad at top universities.","benefits":"Full tuition fees; visa fees; annual maintenance allowance; airfare — for 4 years PhD study abroad","min_age":18,"max_age":35,"income_limit":600000,"genders":["all"],"states":["all"],"castes":["SC"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","caste","basic"],"official_url":"https://nosmsje.gov.in"},
  {"name":"PM Vaya Vandana Yojana","description":"Pension scheme for senior citizens providing assured return and regular pension for 10 years.","benefits":"Assured 7.4% return; monthly pension from Rs.1,000 to Rs.9,250; lump sum investment up to Rs.15 lakh","min_age":60,"max_age":100,"income_limit":2000000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Retired"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://licindia.in"},
  {"name":"Antyodaya Anna Yojana","description":"Provides 35 kg of foodgrains per family per month to the poorest of poor households at highly subsidised rates.","benefits":"35 kg foodgrains/family/month: rice at Rs.3/kg, wheat at Rs.2/kg, coarse grains at Rs.1/kg","min_age":0,"max_age":100,"income_limit":50000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Agricultural Laborer","Daily Wage Worker","Homemaker","Unemployed"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://dfpd.gov.in"},
  {"name":"Swachh Bharat Mission (Grameen)","description":"Aims to achieve open defecation free status by constructing individual household toilets in rural areas.","benefits":"Rs.12,000 financial assistance for construction of individual household toilet; linked to MGNREGS","min_age":18,"max_age":100,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://swachhbharatmission.gov.in"},
  {"name":"PM Awas Yojana (Grameen)","description":"Housing assistance for homeless and those living in kutcha houses in rural areas under PMAY-G.","benefits":"Rs.1.2 lakh in plain areas; Rs.1.3 lakh in hilly/difficult areas; 90–95 days MGNREGA labour wages","min_age":18,"max_age":100,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Agricultural Laborer","Daily Wage Worker","Farmer"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmayg.nic.in"},
  {"name":"National Food Security Act (NFSA)","description":"Provides subsidised foodgrains to approximately two-thirds of India's population under priority households.","benefits":"5 kg foodgrains/person/month at Rs.3/kg rice, Rs.2/kg wheat, Rs.1/kg coarse grains","min_age":0,"max_age":100,"income_limit":100000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://dfpd.gov.in"},
  {"name":"Rashtriya Swasthya Bima Yojana","description":"Health insurance scheme for workers in unorganised sector providing cashless hospitalisation cover.","benefits":"Rs.30,000 annual health cover per family; cashless treatment at empanelled hospitals; transport allowance","min_age":0,"max_age":100,"income_limit":150000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Agricultural Laborer","Daily Wage Worker"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://rsby.gov.in"},
  {"name":"Mahila Shakti Kendra","description":"Empowers rural women through community participation and creates an environment for holistic development.","benefits":"Skill development training; digital literacy; awareness on legal rights; access to government schemes","min_age":18,"max_age":60,"income_limit":300000,"genders":["Female"],"states":["all"],"castes":["all"],"occupations":["Homemaker","Agricultural Laborer","Self-employed"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://wcd.nic.in"},
  {"name":"PM Scholarship Scheme (CAPF)","description":"Scholarship for wards and widows of Central Armed Police Forces and Railway Protection Force personnel.","benefits":"Rs.3,000/month for boys; Rs.3,500/month for girls — for professional degree courses for 4–5 years","min_age":18,"max_age":25,"income_limit":600000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://scholarships.gov.in"},
  {"name":"National Handicapped Finance Development Corporation","description":"Concessional loans for persons with disabilities to start self-employment and income-generating activities.","benefits":"Loans up to Rs.25 lakh at 5% interest for general disability; 4% for women with disability","min_age":18,"max_age":55,"income_limit":300000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Self-employed","Unemployed"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://nhfdc.nic.in"},
  {"name":"Widow Remarriage Scheme","description":"Financial assistance to widows below poverty line for remarriage to encourage social rehabilitation.","benefits":"One-time financial assistance of Rs.25,000–50,000 (varies by state) for remarriage","min_age":18,"max_age":50,"income_limit":100000,"genders":["Female"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://wcd.nic.in"},
  {"name":"Central Sector Scheme for Top Class Education (SC)","description":"Full financial support to meritorious SC students to pursue quality higher education.","benefits":"Full tuition fee; non-refundable charges; maintenance Rs.2,220/month; books Rs.20,000/year","min_age":18,"max_age":30,"income_limit":800000,"genders":["all"],"states":["all"],"castes":["SC"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","caste"],"official_url":"https://scholarships.gov.in"},
  {"name":"Soil Health Card Scheme","description":"Provides soil health cards to farmers carrying crop-wise recommendations of nutrients and fertilisers.","benefits":"Free soil testing; crop-wise nutrient recommendations; leads to 8–10% reduction in fertiliser use","min_age":18,"max_age":100,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Farmer"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://soilhealth.dac.gov.in"},
  {"name":"PM Gram Sadak Yojana","description":"Provides all-weather road connectivity to unconnected rural habitations and upgrades existing rural roads.","benefits":"Community benefit — all-weather road access to previously unconnected habitations","min_age":0,"max_age":100,"income_limit":500000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://pmgsy.nic.in"},
  {"name":"National Rural Livelihood Mission (NRLM)","description":"Reduces poverty by enabling poor households to access profitable self-employment and skilled wage employment.","benefits":"Interest subvention on SHG loans; skill training; bank linkage; revolving fund up to Rs.15,000","min_age":18,"max_age":60,"income_limit":200000,"genders":["Female"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Homemaker","Agricultural Laborer","Self-employed"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://aajeevika.gov.in"},
  {"name":"Integrated Child Development Services","description":"Provides supplementary nutrition, immunisation, health check-up, referral services and pre-school education to children.","benefits":"Supplementary nutrition; health checkups; immunisation; pre-school non-formal education for 3–6 year olds","min_age":0,"max_age":6,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://wcd.nic.in"},
  {"name":"Senior Citizen Savings Scheme","description":"Provides regular income to senior citizens through a high-interest savings scheme with quarterly payouts.","benefits":"8.2% interest per annum; quarterly payouts; tax benefit under Section 80C; up to Rs.30 lakh deposit","min_age":60,"max_age":100,"income_limit":2000000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Retired"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://nsiindia.gov.in"},
  {"name":"PM Digital Saksharta Abhiyan","description":"Makes six crore rural household members digitally literate by providing training on digital devices and internet.","benefits":"Free digital literacy training; certificate on completion; access to government e-services","min_age":14,"max_age":60,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://pmgdisha.in"},
  {"name":"Rashtriya Vayoshri Yojana","description":"Provides physical aids and assistive living devices to senior citizens belonging to BPL category.","benefits":"Free walking stick, elbow crutches, tripod/quadpod, wheelchair, hearing aids, spectacles","min_age":60,"max_age":100,"income_limit":100000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Retired"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://msje.gov.in"},
  {"name":"National Scholarship Scheme for Transgender Students","description":"Provides scholarships to transgender students to support their education and promote social inclusion.","benefits":"Rs.13,500 per year for class 9–12; post-secondary: Rs.22,000 per year — includes all charges","min_age":10,"max_age":30,"income_limit":250000,"genders":["Other"],"states":["all"],"castes":["all"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://scholarships.gov.in"},
  {"name":"Dhan Laxmi Scheme","description":"Cash transfers to families conditioned on meeting requirements for registration of birth, immunisation and education of the girl child.","benefits":"Up to Rs.5,000 in installments for girl child birth registration, immunisation, school enrollment and retention","min_age":0,"max_age":18,"income_limit":200000,"genders":["Female"],"states":["Chhattisgarh"],"castes":["SC","ST","OBC"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","dob","income"],"official_url":"https://wcd.nic.in"},
  {"name":"Ladli Laxmi Scheme","description":"Madhya Pradesh scheme for improving educational and economic status of girls through financial support.","benefits":"Rs.1,18,000 total: installments at class 6, 9, 11 entry; Rs.25,000 lump sum at age 21 on marriage","min_age":0,"max_age":21,"income_limit":500000,"genders":["Female"],"states":["Madhya Pradesh"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","dob"],"official_url":"https://ladlilaxmi.mp.gov.in"},
  {"name":"PM Kisan Maandhan Yojana","description":"Old age pension scheme providing Rs.3,000/month after age 60 to small and marginal farmers.","benefits":"Rs.3,000/month pension after 60; spouse eligible for Rs.1,500/month; government matches contribution","min_age":18,"max_age":40,"income_limit":200000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Farmer"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://pmkmy.gov.in"},
  {"name":"National Means Cum Merit Scholarship (NMMS)","description":"Scholarship to meritorious students of economically weaker sections to arrest their dropout at class VIII.","benefits":"Rs.12,000 per year from class IX to XII; paid directly to student bank account; renewable annually","min_age":13,"max_age":17,"income_limit":150000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Student"],"religions":["all"],"required_docs":["aadhar","income"],"official_url":"https://scholarships.gov.in"},
  {"name":"e-Shram Portal Registration","description":"National database of unorganised workers providing accident insurance and access to all social security schemes.","benefits":"Rs.2 lakh accident insurance; priority access to government welfare schemes; portable benefit account","min_age":16,"max_age":59,"income_limit":300000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Agricultural Laborer","Daily Wage Worker","Self-employed","Homemaker"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://eshram.gov.in"},
  {"name":"PM Garib Kalyan Anna Yojana","description":"Provides free foodgrains to beneficiaries under National Food Security Act — 5 kg per person per month free.","benefits":"5 kg free rice or wheat per person per month over and above NFSA entitlement — no cost to beneficiary","min_age":0,"max_age":100,"income_limit":100000,"genders":["all"],"states":["all"],"castes":["SC","ST","OBC"],"occupations":["Agricultural Laborer","Daily Wage Worker","Homemaker","Unemployed","Farmer"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://dfpd.gov.in"},
  {"name":"Indira Gandhi National Old Age Pension","description":"Monthly pension to BPL senior citizens aged 60 and above under National Social Assistance Programme.","benefits":"Rs.200/month for ages 60–79; Rs.500/month for ages 80 and above — direct bank transfer","min_age":60,"max_age":100,"income_limit":100000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["Retired","Unemployed"],"religions":["all"],"required_docs":["aadhar","income","dob"],"official_url":"https://nsap.nic.in"},
  {"name":"Indira Gandhi National Widow Pension","description":"Monthly pension to BPL widows aged 40–79 under National Social Assistance Programme.","benefits":"Rs.300/month direct bank transfer; eligible for other NSAP benefits simultaneously","min_age":40,"max_age":79,"income_limit":100000,"genders":["Female"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar","income","basic"],"official_url":"https://nsap.nic.in"},
  {"name":"PM Jan Dhan Yojana","description":"Financial inclusion programme ensuring access to financial services — banking, insurance, pension and credit.","benefits":"Zero balance savings account; Rs.1 lakh accident cover; Rs.30,000 life cover; RuPay debit card","min_age":10,"max_age":100,"income_limit":1000000,"genders":["all"],"states":["all"],"castes":["all"],"occupations":["all"],"religions":["all"],"required_docs":["aadhar"],"official_url":"https://pmjdy.gov.in"}
]

def load_schemes():
    print(f"Loading {len(SCHEMES)} schemes into Supabase...")
    
    # Clear existing schemes to avoid duplicates
    existing = supabase.table("schemes").select("id, name").execute()
    existing_names = {s["name"] for s in existing.data}
    
    inserted = 0
    skipped = 0
    errors = 0

    for s in SCHEMES:
        if s["name"] in existing_names:
            skipped += 1
            continue
        try:
            supabase.table("schemes").insert(s).execute()
            inserted += 1
            print(f"  ✓ {s['name']}")
        except Exception as e:
            errors += 1
            print(f"  ✗ {s['name']}: {e}")

    print(f"\nDone — {inserted} inserted, {skipped} skipped (already exist), {errors} errors")

if __name__ == "__main__":
    load_schemes()